concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "mk7-runner"
  url = "http://gitlab.it/"
  id = 757
  token = "_zY5fX_UgPWEnqy9zkzX"
  token_obtained_at = 2023-02-23T08:48:42Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"

[[runners]]
  name = "mk7-docker-runner"
  url = "http://gitlab.it/"
  id = 758
  token = "fxtNeEgapkFG55NPwRKV"
  token_obtained_at = 2023-02-23T08:51:56Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "node:19-alpine3.16"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    pull_policy = ["if-not-present"]
    shm_size = 0

[[runners]]
  name = "mk7-docker-new"
  url = "http://gitlab.it/"
  id = 759
  token = "B1Q8j2_HCxJDFojkFPY1"
  token_obtained_at = 2023-03-01T13:41:39Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "node:19"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    pull_policy = ["if-not-present"]
    shm_size = 0

[[runners]]
  name = "mk7-docker"
  url = "http://localhost:8929/"
  id = 1
  token = "nE4xszBSfb8XYmUsM_sU"
  token_obtained_at = 2023-03-16T10:51:14Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "node:19"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    pull_policy = ["if-not-present"]
    shm_size = 0

[[runners]]
  name = "mk7-pc"
  url = "http://localhost:8929/"
  id = 2
  token = "LrdP7nT8eQ58oib4ysz9"
  token_obtained_at = 2023-03-16T12:21:12Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"

[[runners]]
  name = "docker-ip"
  url = "http://172.16.58.11:8929/"
  id = 3
  token = "mCSpv82n351zmBnR_eon"
  token_obtained_at = 2023-03-16T13:59:05Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "node:19"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
	pull_policy = ["if-not-present"]
    volumes = ["/cache"]
    shm_size = 0
